apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.serviceName }}
  namespace: siembol
spec:
  secretName: "{{ .Values.serviceName }}-{{ .Values.environment }}-tls"
  issuerRef:
    kind: ClusterIssuer
    name: k8s-cluster-issuer
  commonName: {{ .Values.hostname }}
  dnsNames:
  - {{ .Values.hostname }}