apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  annotations:
    ingress.io/ingress.allow-http: "true"
    ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    ingress.kubernetes.io/ssl-passthrough-http-port: "80"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts: 
    - {{ .Values.hostname }}
    secretName: config-editor-ui-qa-tls
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: 80
