apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  tls:
    - hosts:
      - {{ .Values.appName }}.REDACTED-CLUSTER
      - {{ .Values.fqdn }}
      secretName: {{ .Values.appName}}-tls
  rules:
  - host: {{ .Values.appName }}.REDACTED-CLUSTER
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 8089
  - host: {{ .Values.fqdn }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 8089
