apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rest.appName }} 
data:
  application.properties: |-
{{ .Files.Get .Values.rest.applicationProperties | indent 4 }}
  gitconfig: |-
{{ .Files.Get .Values.rest.gitConfig | indent 4 }}
