apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.rest.appName }}
  name: {{ .Values.rest.appName }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.rest.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.rest.appName}}
      name: {{ .Values.rest.appName }}
    spec:
      containers:
      - image: {{ .Values.rest.image.repository }}:{{ .Values.rest.image.tag }}
        workingDir: {{ .Values.rest.mountPath }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.rest.imagePullPolicy | quote }}
        name: {{ .Values.rest.appName }}
        ports:
          - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          runAsUser: 101
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8089
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8089
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        env:
        {{ if .Values.tls.enabled -}}
        - name: JAVA_OPTS
          value: -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts 
        {{ end }}
        - name: GIT_PSWD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rest.appName }}-secrets
              key: git
        volumeMounts:
        {{ if .Values.tls.enabled -}}
        - name: cacerts
          mountPath: /etc/ssl/certs/java/cacerts
          subPath: cacerts
          readOnly: true        
        {{ end -}}
        - name: {{ .Values.rest.appName }}
          mountPath: /etc/gitconfig
          subPath: gitconfig 
          readOnly: true
        - name: {{ .Values.rest.appName }}
          mountPath: {{ .Values.rest.mountPath }}/application.properties
          subPath: application.properties
          readOnly: true
        - name: rules-dir
          mountPath: /rules
      volumes:
      {{ if .Values.tls.enabled -}}
      - name: cacerts
        secret:
          secretName: certs
      {{- end }}
      - name: {{ .Values.rest.appName }}
        configMap:
          name: {{ .Values.rest.appName }}
          items:
          - key: application.properties
            path: application.properties
      - name: rules-dir
        emptyDir: {}
      terminationGracePeriodSeconds: 300
