apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.manager.appName }}
  name: {{ .Values.manager.appName }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.manager.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.manager.appName}}
      name: {{ .Values.manager.appName }}
    spec:
      serviceAccountName: {{ .Values.manager.serviceAccount }}
      containers:
      - image: {{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}
        workingDir: {{ .Values.manager.mountPath }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.manager.imagePullPolicy | quote }}
        name: {{ .Values.manager.appName }}
        ports:
          - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          runAsUser: 101
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8082
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8082
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        env:
        {{ if .Values.tls.enabled -}}
        - name: JAVA_OPTS
          value: -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts 
        {{ end }}
        volumeMounts:
        {{ if .Values.tls.enabled -}}
        - name: cacerts
          mountPath: /etc/ssl/certs/java/cacerts
          subPath: cacerts
          readOnly: true        
        {{ end -}}
        - name: {{ .Values.manager.appName }}
          mountPath: {{ .Values.manager.mountPath }}/application.properties
          subPath: application.properties
          readOnly: true
        - name: {{ .Values.manager.appName }}
          mountPath: {{ .Values.manager.mountPath }}/storm-submit.yaml
          subPath: storm-submit.yaml
          readOnly: true
      volumes:
      {{ if .Values.tls.enabled -}}
      - name: cacerts
        secret:
          secretName: cacerts
      {{- end }}
      - name: {{ .Values.manager.appName }}
        configMap:
          name: {{ .Values.manager.appName }}
      terminationGracePeriodSeconds: 300
