apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.serviceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.manager.appName }}-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.manager.appName }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccount }}