name: CI

on:
  push:
    branches:
      - master

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Build with Maven
        run: mvn -B package
      - name: Upload alerting-storm jar
        uses: actions/upload-artifact@v2
        with:
          name: alerting-storm
          path: alerting/alerting-storm/target/alerting-storm-*.jar
      - name: Upload enriching-storm jar
        uses: actions/upload-artifact@v2
        with:
          name: enriching-storm
          path: enriching/enriching-storm/target/enriching-storm-*.jar
      - name: Upload parsing-storm jar
        uses: actions/upload-artifact@v2
        with:
          name: parsing-storm
          path: parsing/parsing-storm/target/parsing-storm-*.jar
      - name: Upload config-editor-rest jar
        uses: actions/upload-artifact@v2
        with:
          name: config-editor-rest
          path: config-editor/config-editor-rest/target/config-editor-rest-*.jar

  build-docker-storm:
    runs-on: ubuntu-latest
    needs: build-java
    strategy:
      matrix:
        component: [alerting-storm, enriching-storm, parsing-storm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.component }}
          path: deployment/docker
      - name: Get component info
        id: info
        run: |
          [xml]$xml = Get-Content ./*/${{ matrix.component}}/pom.xml
          echo "::set-output name=version::$($xml.project.parent.version)"
          echo "::set-output name=class::$($xml.project.build.plugins.plugin.executions.execution.configuration.transformers.transformer.mainClass)"
        shell: pwsh
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: gresearchdev/siembol-${{ matrix.component }}
          path: deployment/docker
          dockerfile: deployment/docker/Dockerfile.storm
          build_args: JAR=${{ matrix.component }}-${{ steps.info.outputs.version }}.jar,CLASS=${{ steps.info.outputs.class }}
          always_pull: true
          add_git_labels: true
          tags: latest,${{ steps.info.outputs.version }}

  build-docker-config-editor-rest:
    runs-on: ubuntu-latest
    needs: build-java
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: config-editor-rest
          path: deployment/docker/config-editor-rest
      - name: Copy config defaults
        run: |
          cp config/config-editor-rest/application.properties deployment/docker/config-editor-rest/
          mkdir deployment/docker/config-editor-rest/ui-config
          cp config/config-editor-rest/*.json deployment/docker/config-editor-rest/ui-config/
      - name: Get component info
        id: info
        run: |
          [xml]$xml = Get-Content ./config-editor/config-editor-rest/pom.xml
          echo "::set-output name=version::$($xml.project.parent.version)"
        shell: pwsh
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: gresearchdev/siembol-config-editor-rest
          path: deployment/docker
          dockerfile: deployment/docker/Dockerfile.config-editor-rest
          build_args: VERSION=${{ steps.info.outputs.version }}
          always_pull: true
          add_git_labels: true
          tags: latest,${{ steps.info.outputs.version }}

  build-js-config-editor-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config-editor/config-editor-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache NPM packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-config-editor-ui-${{ hashFiles('config-editor/config-editor-ui/package.json') }}
          restore-keys: |
            npm-config-editor-ui-
      - name: Install NPM packages
        run: |
          npm install typescript@3.7.5
          npm ci
      - name: Testing
        run: npm run test-ci
      - name: Generate build-info.json
        run: |
          jq "{appName: \"Config Editor UI\", appVersion: .version, angularVersion: .dependencies[\"@angular/core\"], buildDate: \"$(date -u +%Y%m%d-%H:%M:%S)\", siembolCompileTimeVersion: .siembolCompileTimeVersion}" package.json > src/assets/build-info.json
      - name: Build
        run: npm run build-prod
      - name: Copy config defaults
        run: cp -r ../../config/config-editor-ui dist/config
      - name: Uploading dist
        uses: actions/upload-artifact@v2
        with:
          name: config-editor-ui
          path: config-editor/config-editor-ui/dist

  build-docker-config-editor-ui:
    runs-on: ubuntu-latest
    needs: build-js-config-editor-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: config-editor-ui
          path: deployment/docker/config-editor-ui
      - name: Get version
        id: info
        run: echo "::set-output name=version::$(jq -r .appVersion deployment/docker/config-editor-ui/assets/build-info.json)"
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: gresearchdev/siembol-config-editor-ui
          path: deployment/docker
          dockerfile: deployment/docker/Dockerfile.config-editor-ui
          always_pull: true
          add_git_labels: true
          tags: latest,${{ steps.info.outputs.version }}
